In [2]:
# !pip install mysqlclient 
import pandas as pd
import sqlalchemy
from sqlalchemy import create_engine 
import mysql

In [3]:
csv = 'YardvilleTags2018.csv'
Yardville_tagsDF = pd.read_csv(csv)
Yardville_tagsDF.head()

,X,Y,FID,Citation_N,Date,Address,Latitude,Longitude,Ordinance,Ordinanc_1,Neighborho,Community,Ward,Snow_Em_Na,Day_ID,Tow_Distri
0,-93.288902,45.043098,3001,271118359139,2018-02-26T00:00:00.000Z,4834 CAMDEN AVE N,45.043098,-93.288902,478.1000(b),Snow emergency parking restrictions - even num...,Lind - Bohanon,Camden,4,Xerxes,2,1
1,-93.288895,45.043255,3002,271118359140,2018-02-26T00:00:00.000Z,4838 CAMDEN AVE N,45.043255,-93.288895,478.1000(b),Snow emergency parking restrictions - even num...,Lind - Bohanon,Camden,4,Xerxes,2,1
2,-93.271568,44.914726,3003,271118343680,2018-02-26T00:00:00.000Z,4844 CLINTON AVE S,44.914726,-93.271568,478.1000(b),Snow emergency parking restrictions - even num...,Field,Nokomis,8,Xerxes,2,5
3,-93.290146,45.043591,3004,271118359150,2018-02-26T00:00:00.000Z,4850 ALDRICH AVE N,45.043591,-93.290146,478.1000(b),Snow emergency parking restrictions - even num...,Lind - Bohanon,Camden,4,Xerxes,2,1
4,-93.288879,45.043571,3005,271118359141,2018-02-26T00:00:00.000Z,4854 CAMDEN AVE N,45.043571,-93.288879,478.1000(b),Snow emergency parking restrictions - even num...,Lind - Bohanon,Camden,4,Xerxes,2,1

In [4]:
tempdf = Yardville_tagsDF.copy()

In [5]:
tempdf = tempdf.loc[:,["FID",
"Citation_N",
"Snow_Em_Na",
"Date",
"Address",
"Latitude",
"Longitude",
"Day_ID",
"Ordinance",
'Ordinanc_1',
'Ward',
"Neighborho",
"Community",
"Tow_Distri"]]

In [6]:
tempdf.head()

,FID,Citation_N,Snow_Em_Na,Date,Address,Latitude,Longitude,Day_ID,Ordinance,Ordinanc_1,Ward,Neighborho,Community,Tow_Distri
0,3001,271118359139,Xerxes,2018-02-26T00:00:00.000Z,4834 CAMDEN AVE N,45.043098,-93.288902,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
1,3002,271118359140,Xerxes,2018-02-26T00:00:00.000Z,4838 CAMDEN AVE N,45.043255,-93.288895,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
2,3003,271118343680,Xerxes,2018-02-26T00:00:00.000Z,4844 CLINTON AVE S,44.914726,-93.271568,2,478.1000(b),Snow emergency parking restrictions - even num...,8,Field,Nokomis,5
3,3004,271118359150,Xerxes,2018-02-26T00:00:00.000Z,4850 ALDRICH AVE N,45.043591,-93.290146,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
4,3005,271118359141,Xerxes,2018-02-26T00:00:00.000Z,4854 CAMDEN AVE N,45.043571,-93.288879,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1

In [7]:
tempdf = tempdf.rename(
    columns={"Snow_Em_Na": "snow_emergency_name",
            "Citation_N": "citation",
            "Date": "service_date",
            "Address": "address",
            "Latitude": "latitude",
            "Longitude": "longitude",
            "Day_ID": "day_id",
            "Ordinance": "ordinance_id",
            "Ordinanc_1": "ordinance_desc",
            "Ward": "ward",
            "Neighborho": "neighborhood",
            "Community": "community",
            "Tow_Distri": "tow_district"})

In [8]:
tempdf.head()

,FID,citation,snow_emergency_name,service_date,address,latitude,longitude,day_id,ordinance_id,ordinance_desc,ward,neighborhood,community,tow_district
0,3001,271118359139,Xerxes,2018-02-26T00:00:00.000Z,4834 CAMDEN AVE N,45.043098,-93.288902,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
1,3002,271118359140,Xerxes,2018-02-26T00:00:00.000Z,4838 CAMDEN AVE N,45.043255,-93.288895,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
2,3003,271118343680,Xerxes,2018-02-26T00:00:00.000Z,4844 CLINTON AVE S,44.914726,-93.271568,2,478.1000(b),Snow emergency parking restrictions - even num...,8,Field,Nokomis,5
3,3004,271118359150,Xerxes,2018-02-26T00:00:00.000Z,4850 ALDRICH AVE N,45.043591,-93.290146,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
4,3005,271118359141,Xerxes,2018-02-26T00:00:00.000Z,4854 CAMDEN AVE N,45.043571,-93.288879,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1

In [11]:
len(tempdf.FID.unique())

3857

In [19]:
tempdf['service_date']=pd.to_datetime(tempdf['service_date'].astype(str).str[:10])

In [30]:
tempdf['latitude']=round(tempdf['latitude'],3)

In [31]:
tempdf['longitude']=round(tempdf['longitude'],3)

In [32]:
finaldf = tempdf
finaldf.head()

,FID,citation,snow_emergency_name,service_date,address,latitude,longitude,day_id,ordinance_id,ordinance_desc,ward,neighborhood,community,tow_district
0,3001,271118359139,Xerxes,2018-02-26,4834 CAMDEN AVE N,45.043,-93.289,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
1,3002,271118359140,Xerxes,2018-02-26,4838 CAMDEN AVE N,45.043,-93.289,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
2,3003,271118343680,Xerxes,2018-02-26,4844 CLINTON AVE S,44.915,-93.272,2,478.1000(b),Snow emergency parking restrictions - even num...,8,Field,Nokomis,5
3,3004,271118359150,Xerxes,2018-02-26,4850 ALDRICH AVE N,45.044,-93.290,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1
4,3005,271118359141,Xerxes,2018-02-26,4854 CAMDEN AVE N,45.044,-93.289,2,478.1000(b),Snow emergency parking restrictions - even num...,4,Lind - Bohanon,Camden,1

In [39]:

# SQL Alchemy
from sqlalchemy import create_engine

# PyMySQL
import pymysql
pymysql.install_as_MySQLdb()
# Create Engine and Pass in MySQL Connection
engine = create_engine("mysql://root:sadie9564@localhost/snow_emergency_db")

In [41]:
finaldf = tempdf.to_sql(name="yardville_tags_base", con=engine, if_exists='append')

InternalError: (pymysql.err.InternalError) (1054, "Unknown column 'index' in 'field list'") [SQL: 'INSERT INTO yardville_tags_base (`index`, `FID`, citation, snow_emergency_name, service_date, address, latitude, longitude, day_id, ordinance_id, ordinance_desc, ward, neighborhood, community, tow_district) VALUES (%(index)s, %(FID)s, %(citation)s, %(snow_emergency_name)s, %(service_date)s, %(address)s, %(latitude)s, %(longitude)s, %(day_id)s, %(ordinance_id)s, %(ordinance_desc)s, %(ward)s, %(neighborhood)s, %(community)s, %(tow_district)s)'] [parameters: ({'index': 0, 'FID': 3001, 'citation': 271118359139, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4834 CAMDEN AVE N', 'latitude': 45.043, 'longitude': -93.289, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 4, 'neighborhood': 'Lind - Bohanon', 'community': 'Camden', 'tow_district': 1}, {'index': 1, 'FID': 3002, 'citation': 271118359140, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4838 CAMDEN AVE N', 'latitude': 45.043, 'longitude': -93.289, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 4, 'neighborhood': 'Lind - Bohanon', 'community': 'Camden', 'tow_district': 1}, {'index': 2, 'FID': 3003, 'citation': 271118343680, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4844 CLINTON AVE S', 'latitude': 44.915, 'longitude': -93.272, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 8, 'neighborhood': 'Field', 'community': 'Nokomis', 'tow_district': 5}, {'index': 3, 'FID': 3004, 'citation': 271118359150, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4850 ALDRICH AVE N', 'latitude': 45.044, 'longitude': -93.29, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 4, 'neighborhood': 'Lind - Bohanon', 'community': 'Camden', 'tow_district': 1}, {'index': 4, 'FID': 3005, 'citation': 271118359141, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4854 CAMDEN AVE N', 'latitude': 45.044, 'longitude': -93.289, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 4, 'neighborhood': 'Lind - Bohanon', 'community': 'Camden', 'tow_district': 1}, {'index': 5, 'FID': 3006, 'citation': 271118355030, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4900 53RD ST E', 'latitude': 44.908, 'longitude': -93.204, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 12, 'neighborhood': 'Minnehaha', 'community': 'Nokomis', 'tow_district': 6}, {'index': 6, 'FID': 3007, 'citation': 271118357323, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4904 53RD ST E', 'latitude': 44.908, 'longitude': -93.204, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 12, 'neighborhood': 'Minnehaha', 'community': 'Nokomis', 'tow_district': 6}, {'index': 7, 'FID': 3008, 'citation': 271118354803, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 26, 0, 0), 'address': '4910 MORGAN AVE S', 'latitude': 44.914, 'longitude': -93.305, 'day_id': 2, 'ordinance_id': '478.1000(b)', 'ordinance_desc': 'Snow emergency parking restrictions - even number address', 'ward': 13, 'neighborhood': 'Lynnhurst', 'community': 'Southwest', 'tow_district': 5}  ... displaying 10 of 3857 total bound parameter sets ...  {'index': 3855, 'FID': 999, 'citation': 271118340755, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 27, 0, 0), 'address': '2141 MOUNT VIEW AVE', 'latitude': 44.972, 'longitude': -93.308, 'day_id': 3, 'ordinance_id': '478.1000(c)', 'ordinance_desc': 'Snow emergency parking restrictions - odd number address', 'ward': 7, 'neighborhood': 'Bryn - Mawr', 'community': 'Calhoun Isle', 'tow_district': 3}, {'index': 3856, 'FID': 1000, 'citation': 271118363950, 'snow_emergency_name': 'Xerxes', 'service_date': datetime.datetime(2018, 2, 27, 0, 0), 'address': '215 18TH ST E', 'latitude': 44.965, 'longitude': -93.273, 'day_id': 3, 'ordinance_id': '478.1000(c)', 'ordinance_desc': 'Snow emergency parking restrictions - odd number address', 'ward': 6, 'neighborhood': "Steven's Square - Loring Heights", 'community': 'Central', 'tow_district': 3})] (Background on this error at: http://sqlalche.me/e/2j85)